spring.application.name=kinukollu-backend

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:kinukollu}
spring.datasource.username=${PGUSER:kinukollu_admin}
spring.datasource.password=${PGPASSWORD:KinukolluKiranInukollu}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080


anthropic.api.key=${ANTHROPIC_API_KEY}
anthropic.api.url=https://api.anthropic.com/v1/messages
anthropic.api.model=claude-sonnet-4-6

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
